<?php
define('DRAGONPAY_DEMO', 'http://test.dragonpay.ph/Pay.aspx');
define('DRAGONPAY_LIVE', 'https://secure.dragonpay.ph/Pay.aspx');
/**
 * @file
 * Process payments using DragonPay PayGate.
 */

/**
 * Implementation of hook_menu().
 */
function uc_dragonpay_menu() {
  $items = array();

  $items['dragonpay/success'] = array(
    'title' => 'Order complete',
    'page callback' => 'uc_dragonpay_success',
    'access callback' => 'uc_dragonpay_access',
    'type' => MENU_CALLBACK,
    'file' => 'uc_dragonpay.pages.inc',
  );
  $items['dragonpay/fail'] = array(
    'title' => 'Order complete',
    'page callback' => 'uc_dragonpay_fail',
    'access callback' => 'uc_dragonpay_access',
    'type' => MENU_CALLBACK,
    'file' => 'uc_dragonpay.pages.inc',
  );
  $items['dragonpay/cancel'] = array(
    'title' => 'Order complete',
    'page callback' => 'uc_dragonpay_cancel',
    'access callback' => 'uc_dragonpay_access',
    'type' => MENU_CALLBACK,
    'file' => 'uc_dragonpay.pages.inc',
  );
  // The main handler for complete transaction.
  $items['dragonpay/datafeed'] = array(
    'title' => 'Order complete',
    'page callback' => 'uc_dragonpay_datafeed',
    'access callback' => 'uc_dragonpay_access',
    'type' => MENU_CALLBACK,
    'file' => 'uc_dragonpay.pages.inc',
  );

  return $items;
}

/**
 * Make sure anyone can complete their DragonPay PayGate orders.
 * Full access
 */
function uc_dragonpay_access() {
  return TRUE;
}

/**
 * Implementation of hook_init().
 */
function uc_dragonpay_init() {
  global $conf;
  $conf['i18n_variables'][] = 'uc_dragonpay_checkout_button';
}

/**
 * Implementation of hook_form_alter().
 */
function uc_dragonpay_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'uc_cart_checkout_review_form' && ($order_id = intval($_SESSION['cart_order'])) > 0) {
    $order = uc_order_load($order_id);

    if ($order->payment_method == 'dragonpay') {
      unset($form['submit']);
      $form['#prefix'] = '<table id="two-checkout-review-table"><tr><td>';
      $form['#suffix'] = '</td><td>'. drupal_get_form('uc_dragonpay_form', $order) .'</td></tr></table>';
    }
  }
}

/**
 * Implementation of hook_payment_method().
 */
function uc_dragonpay_payment_method() {
  $gateways[] = array(
    'id' => 'dragonpay',
    'name' => t('DragonPay PayGate'),
    'title' => t('DragonPay PayGate - provides secure, multi-channel, multi-lingual and multi-currency payment services.'),
    'review' => t('DragonPay Client Post'),
    'desc' => t('Process credit card or PayPal payments using DragonPay PayGate.'),
    'callback' => 'uc_payment_method_dragonpay',
    'weight' => 1,
    'checkout' => FALSE,
    'no_gateway' => TRUE,
  );

  return $gateways;
}

/**
 * Callback for payment gateway settings.
 */
function uc_payment_method_dragonpay($op, &$arg1) {
  switch ($op) {
    case 'order-view':
      $payref = db_result(db_query("SELECT payref FROM {uc_dragonpay_datafeed} WHERE ref = %d ORDER BY cdatetime ASC", $arg1->order_id));
      if (empty($payref)) {
        $payref = t('Unknown');
      }
      return t('DragonPay Payment Reference Number:<br />@payref', array('@payref' => $payref));

    case 'settings':
      $form['dragonpay']['uc_dragonpay_id'] = array(
        '#type' => 'textfield',
        '#title' => t('DragonPay ID'),
        '#description' => t('The merchant id used for the DragonPay service.'),
        '#default_value' => variable_get('uc_dragonpay_id', '1'),
      );
      $form['dragonpay']['uc_dragonpay_paytype'] = array(
        '#type' => 'select',
        '#title' => t('DragonPay Payment Type'),
        '#description' => t('Choose type of payment'),
        '#options' => array(
				  'ALL' => t('All the available payment method'),
					'CC'  => t('Credit Card Payment'),
					'PPS' => t('DragonPay PPS Payment'),
					'PAYPAL' => t('PayPal By DragonPay Payment'),
					'CUP' => t('DragonPay CUP Payment'),
					'GCash' => t('Globe GCash Mobile Payment'),
					'BancNet' => t('BancNet Debit Card Payment'),
        ),
        '#default_value' => variable_get('uc_dragonpay_paytype', 'ALL'),
      );
      $form['dragonpay']['uc_dragonpay_handler'] = array(
        '#type' => 'select',
        '#title' => t('DragonPay server'),
        '#description' => t('Sign up for and use a Sandbox account for testing.'),
        '#options' => array(
          DRAGONPAY_DEMO => t('Sandbox'),
          DRAGONPAY_LIVE => t('Live'),
        ),
        '#default_value' => variable_get('uc_dragonpay_handler', DRAGONPAY_DEMO),
      );
      $form['dragonpay']['uc_dragonpay_currency'] = array(
        '#type' => 'select',
        '#title' => t('Currency code'),
        '#description' => t('Transactions can only be processed in one of the listed currencies.'),
        '#options' => array(
				  '608' => 'PHP',
          '344' => 'HKD',
          '840' => 'USD',
          '702' => 'SGD',
          '156' => 'CNY',
          '392' => 'JPY',
          '901' => 'TWD',
          '036' => 'AUD',
          '978' => 'EUR',
          '826' => 'GBP',
          '124' => 'CAD',
        ),
        '#default_value' => variable_get('uc_dragonpay_currency', '608'),
      );
      $form['dragonpay']['uc_dragonpay_language'] = array(
        '#type' => 'select',
        '#title' => t('Language'),
        '#description' => t('Please choose the language page.'),
        '#options' => array(
          'E' => t('English'),
          'C' => t('Traditional Chinese'),
          'X' => t('Simplified Chinese'),
          'K' => t('Korean'),
          'J' => t('Japanese'),
        ),
        '#default_value' => variable_get('uc_dragonpay_language', 'E'),
      );
      $form['dragonpay']['uc_dragonpay_checkout_button'] = array(
        '#type' => 'textfield',
        '#title' => t('Order review submit button text'),
        '#description' => t('Provide DragonPay PayGate specific text for the submit button on the order review page.'),
        '#default_value' => variable_get('uc_2checkout_checkout_button', t('Submit Order')),
      );

      return $form;
  }
}

/**
 * Form to build the submission to DragonPay.com in HTML hidden form.
 */
function uc_dragonpay_form($form_state, $order) {
  $data = array(
	  'orderRef' => $order->order_id,
    'amount' => $order->order_total,
    'currCode' => variable_get('uc_dragonpay_currency', '344'),
    'lang' => variable_get('uc_dragonpay_language', 'E'),
    'cancelUrl' => url('dragonpay/cancel/'. $order->order_id, array('absolute' => TRUE) ),
    'failUrl' => url('dragonpay/fail/'. $order->order_id, array('absolute' => TRUE) ),
    'successUrl' => url('dragonpay/success/'. $order->order_id, array('absolute' => TRUE) ),
    'merchantId' => variable_get('uc_dragonpay_id', '1'),
    'payType' => 'N',
		'payMethod' => variable_get('uc_dragonpay_paytype','ALL'),
//    'actionUrl' => variable_get('uc_dragonpay_handler', DRAGONPAY_DEMO),	
//    'code' => 'dragonpay',
//    'orderId' => $order->order_id,
    'remark' => uc_cart_get_id(),
  );

  $form['#action'] = variable_get('uc_dragonpay_handler', DRAGONPAY_DEMO);

  foreach ($data as $name => $value) {
    if (!empty($value)) {
      $form[$name] = array('#type' => 'hidden', '#value' => $value);
    }
  }

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => variable_get('uc_dragonpay_checkout_button', t('Submit Order')),
  );

  return $form;
}
